### ISSUE TITLE
Delete previous comments before posting a new one

### ISSUE THREAD

**Issue by vhoyer** [jacobbowdoin/comment-test-coverage#4]
What do you think of this idea? I don't want to have a spam of the pull request coverage reports each commit I push to a branch. Feedback, I want feedback haha

**Comment by jacob-8** [comment]
This is important and I have an example of how to do this on another repo. I'll have to integrate it unless you already have the code handy.

**Comment by vhoyer** [comment]
I do have one working, will open a PR for you to see it, that said, I'm curious about your other implementation, wanna share the repo?

**Comment by vhoyer** [comment]
So I've opened my proposal to removing old comments there, still my curiosity instigates me, I'd really appreciate if you could share other ways to doing so :smile:

**Comment by jacob-8** [comment]
Published these changes to the [marketplace](https://github.com/marketplace/actions/comment-test-coverage).

**Comment by jacob-8** [comment]
> So I've opened my proposal to removing old comments there, still my curiosity instigates me, I'd really appreciate if you could share other ways to doing so 😄

@vhoyer I was mistaken, I actually don't have an example of how to do it in code, but rather a GitHub action that I've been using to do it. Feel free to peruse https://github.com/marocchino/sticky-pull-request-comment if you'd like though that action has a whole lot more than is necessary for what you're doing here. Also, see how I'm using the action in https://github.com/jwrunner/hvsb-svelte-kit/blob/master/.github/workflows/deploy-master-push.yml - my usage of it originally came from a Vercel tutorial.

**Comment by vhoyer** [comment]
I think your repo is private, cuz I cannot see it :D
